### ISSUE TITLE
Cannot open load file: org-now

### ISSUE THREAD

**Issue by squiter** [alphapapa/org-now#1]
I'm trying to test your package, but when I run `org-now-refile-to-now` I got the error: `command-execute: Cannot open load file: No such file or directory, org-now`.

This is my configuration: 

```
(use-package org-now
  :bind
  ("<f9> a n" . org-now-refile-to-now)
  ("<f9> a b" . org-now-refile-to-previous-location))
```

I'm using Emacs 26.1 and Org mode 9.1.13.

**Comment by alphapapa** [comment]
I think that's happening because you didn't put `org-now.el` in a directory in your `load-path`.

**Comment by a13** [comment]
@squiter 

You can try quelpa-use-package instead! It allows you to install packages from any source.

```
(use-package org-now
  :ensure t
  :quelpa
  (org-now :repo "alphapapa/org-now" :fetcher github))
```


P.S. don't forget to install quelpa stuff itself
```emacs-lisp
(use-package quelpa)
(use-package quelpa-use-package)
```

**Comment by alphapapa** [comment]
Feel free to ask if you need anything else.
