### ISSUE TITLE
org-now links display full link text

### ISSUE THREAD

**Issue by max6166** [alphapapa/org-now#11]
The issue occurs when I use `org-now-link ` or `org-now-agenda-link `. The link text in the org-now buffer is displayed in full, instead of the normal formatting which only displays the description and hides the link data. 

I correct the appearance by running `org-mode-restart` in the org-now buffer after creating each new link.

In other words, the link appears like this:
```
** [[id:5B90E668-F866-4005-9EFC-BD0E214EB02B][Do this]]
```

when it should be this:

```
** Do this
```

**Comment by alphapapa** [comment]
I've seen Org doing this in other buffers as well.  AFAIK it has nothing to do with org-now because it can happen in any buffer.  I use `C-x x f` to fix it when it happens.  I don't know what causes it, so I can't very well report the bug to Org developers.  If you can, please do.
