### ISSUE TITLE
cl--assertion-failed: Assertion failed: marker

### ISSUE THREAD

**Issue by alex-a-soto** [alphapapa/org-now#6]
### Summary

When using the org-now commands to refile an org-heading to a previous location, an error is displayed: ```cl--assertion-failed: Assertion failed: marker``` and the heading is not refiled.

-------
### Details

- Operating System: NixOS 20.03
- Emacs Version: 27.1
-------
### Steps Taken
1. Refile a org-heading using ```org-now-refile-to-now```or ```org-now-agenda-refile-to-now```
2. Switch to the org-now side window or buffer
3. Refile the org-heading back to it's previous location using ```org-now-agenda-refile-to-previous-location```.
------
### Expected result | Actual result:
When executing the commands ```org-now-agenda-refile-to-previous-location``` to refile the org-heading to its previous location.

**Comment by alphapapa** [comment]
According to step 3, you're using the agenda command in a non-agenda buffer.

**Comment by alex-a-soto** [comment]
Thank you for taking the time to respond. My apologies, I realized this afterward, I assumed that the ```org-now-agenda-refile-to-previous-location``` when not in an org-agenda view would default to the behavior used of ```org-now-refile-to-previous-location```
