### ISSUE TITLE
org-now-location

### ISSUE THREAD

**Issue by iburunat** [alphapapa/org-now#8]
Hi, excellent package.
Just to make sure I am doing things right, I have tried to specify both file and file and headline:

```elisp
(setq org-now-location '(file+headline "~/Dropbox/orgfiles/todo.org/" "TASKS"))
(setq org-now-location '(file "~/Dropbox/orgfiles/todo.org/"))
```

However, I get always a `condition-case: Wrong type argument: stringp, file` (or `file-headline`).
Any help most welcome, thank you.

**Comment by alphapapa** [comment]
Please see `M-x customize-group RET org-now RET`.

**Comment by iburunat** [comment]
Thanks, now I see my syntax was wrong, and it should have been:

```elisp
(setq org-now-location '("~/Dropbox/orgfiles/todo.org/" "TASKS"))
```


I close this issue.
